---
title: "LIU"
output: html_document
date: "2023-05-02"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#1
#Install familiar packages
library(tidyverse);library(lubridate);library(viridis);library(here)

install.packages("rvest")
library(rvest)

install.packages("dataRetrieval")
library(dataRetrieval)

install.packages("tidycensus")
library(tidycensus)
library(dplyr)
library(rvest)
library(ggplot2)

```


```{r html}
url_aq <- "https://wisevoter.com/state-rankings/air-quality-by-state/"
page1 <- read_html(url_aq)
```


```{r pressure, echo=FALSE}
states <- page1 %>% 
  html_nodes("td:nth-child(2)") %>% 
  html_text()

good.air.days <- page1 %>% 
  html_nodes("td:nth-child(3)") %>% 
  html_text()

df_aq <- data.frame(
  States = states,
  Good_Air_Quality_Days_Percentage = good.air.days
)

```

```{r}
url_oil <- "https://wisevoter.com/state-rankings/oil-production-by-state/"
page2 <- read_html(url_oil)

states2 <- page2 %>% 
  html_nodes("td:nth-child(2)") %>% 
  html_text()

oil.production <- page2 %>% 
  html_nodes("td:nth-child(3)") %>% 
  html_text()

df_oil <- data.frame(
  States = states2,
  Oil_Production = oil.production
)
```

```{r}

url_gdp <- "https://wisevoter.com/state-rankings/gdp-by-state/"
page <- read_html(url_gdp)

states3 <- page %>% 
  html_nodes("td:nth-child(2)") %>% 
  html_text()

gdp <- page %>% 
  html_nodes("td:nth-child(3)") %>% 
  html_text()

df_gdp <- data.frame(
  States = states3,
  GDP = gdp
)

```

```{r}

url_sunny <- "https://wisevoter.com/state-rankings/sunniest-states/"
page <- read_html(url_sunny)

states4 <- page %>% 
  html_nodes("td:nth-child(2)") %>% 
  html_text()

sunshine <- page %>% 
  html_nodes("td:nth-child(3)") %>% 
  html_text()

df_sunny <- data.frame(
  States = states4,
  Sunshine = sunshine
)

```

```{r}

url_elec <- "https://wisevoter.com/state-rankings/electricity-cost-by-state/"
page <- read_html(url_elec)

states5 <- page %>% 
  html_nodes("td:nth-child(2)") %>% 
  html_text()

cost <- page %>% 
  html_nodes("td:nth-child(3)") %>% 
  html_text()

df_ecost <- data.frame(
  States = states5,
  Electricity_Cost = cost
)

```

```{r}

url_iq <- "https://wisevoter.com/state-rankings/average-iq-by-state/"
page <- read_html(url_iq)

states6 <- page %>% 
  html_nodes("td:nth-child(2)") %>% 
  html_text()

iq <- page %>% 
  html_nodes("td:nth-child(3)") %>% 
  html_text()

df_iq <- data.frame(
  States = states6,
  Average_IQ = iq
)

```

```{r}
url_party <- "https://wisevoter.com/state-rankings/red-and-blue-states"
page <- read_html(url_party)

states7 <- page %>% 
  html_nodes("td:nth-child(1)") %>% 
  html_text()

rep_vote <- page %>% 
  html_nodes("td:nth-child(3)") %>% 
  html_text()

df_party <- data.frame(
  States = states7,
  Republican_vote = rep_vote
)
```

```{r}
# Merge data frames
state_rankings_df_merge <- Reduce(function(x, y) merge(x, y, by = "States", all = TRUE), 
                   list(df_aq, df_oil, df_gdp, df_sunny, df_ecost, df_iq, df_party))

# View merged data frame
state_rankings_df_merge
```


```{r}
write.csv(state_rankings_df_merge, file = "state rankings_raw.csv",
          row.names = FALSE)
```

```{r}
# read in raw data
state_ranking <- read.csv('state rankings_raw.csv', header = TRUE)
# save a copy of raw data before making changes
state_ranking_raw <- state_ranking

# remove % in good_air_q col
state_ranking$Good_Air_Quality_Days_Percentage <- str_sub(state_ranking$Good_Air_Quality_Days_Percentage, end = -2)
# change chr to numeric
state_ranking$Good_Air_Quality_Days_Percentage <- as.numeric(state_ranking$Good_Air_Quality_Days_Percentage)

# remove unit in oil_production
state_ranking$Oil_Production <- str_sub(state_ranking$Oil_Production, end = -5)
# remove comma 
state_ranking$Oil_Production <- gsub(',','', state_ranking$Oil_Production)
# change chr to numeric
state_ranking$Oil_Production <- as.numeric(state_ranking$Oil_Production)

# remove $ in GDP
state_ranking$GDP <- str_sub(state_ranking$GDP, 2)
# remove comma
state_ranking$GDP <- gsub(',','', state_ranking$GDP)
# change to numeric
state_ranking$GDP <- as.numeric(state_ranking$GDP)

# remove unit in sunshine
state_ranking$Sunshine <- str_sub(state_ranking$Sunshine, end=-6)
# remove comma
state_ranking$Sunshine <- gsub(',','', state_ranking$Sunshine)
# change to numeric
state_ranking$Sunshine <- as.numeric(state_ranking$Sunshine)

# clean electricity_cost
state_ranking$Electricity_Cost <- str_sub(state_ranking$Electricity_Cost, end=-8)
state_ranking$Electricity_Cost <- str_sub(state_ranking$Electricity_Cost, 2)
state_ranking$Electricity_Cost <- as.numeric(state_ranking$Electricity_Cost)

# clean average
state_ranking$Average_IQ <- as.numeric(state_ranking$Average_IQ)

# clean repblican_vote
state_ranking$Republican_vote <- str_sub(state_ranking$Republican_vote, end=-2)
state_ranking$Republican_vote <- as.numeric(state_ranking$Republican_vote)

# create new column: category
state_ranking$party <- with(state_ranking, ifelse(Republican_vote > 50, 1, 0))
```

```{r}
Power_plant <- read.csv(here("data_raw/Power_Plants.csv"), stringsAsFactors = TRUE)

Power_plant[is.na(Power_plant)] <- 0

Power_plant <- Power_plant %>%
  mutate(Total_clean = Bio_MW + Geo_MW + Hydro_MW + HydroPS_MW + Nuclear_MW + Solar_MW + Wind_MW) %>%
  mutate(Total = Total_clean + Coal_MW + NG_MW + Crude_MW)

Clean_energy <- aggregate(cbind(Power_plant$Total_clean, Power_plant$Total), list(Power_plant$State), FUN = sum)
colnames(Clean_energy) <- c("States", "Clean_energy_MW", "Total_MW")
Clean_energy$Clean_percent <- Clean_energy$Clean_energy_MW/Clean_energy$Total_MW

```

```{r}
final_df <- merge(Clean_energy, state_ranking)

```





